build:
  image: latest

python:
  version: 3.6
  pip_install: true
  install:
    - requirements: docsource/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
